---
application:
  name: "docker-waline"
  project: "waline"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "mongowaline"
  version: "3.6"
routers:
- name: "main-docker-waline"
  routes:
  - application_name: "docker-waline"
    paths:
    - "/*"
